cc_library(
    name = "bitset",
    hdrs = [
        "operationbase.h",
        "operation.h",
        "avxoperation.h",
        "bitset.h",
    ],
    deps = [
        "//tt:ttlib"
    ],
    visibility = ["//visibility:public"],
    copts = [
        "-mavx"
    ]
)