cc_library(
    name = "ttlib",
    deps = [
        "//tt/arch:ttarch",
        "//tt/collections:ttalignarray",
        "//tt/def:ttmacrodef",
        "//tt/dout:ttdout"
    ],
    visibility=["//visibility:public"],
)